<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>3559b74f-78dd-411a-96e2-a4adeaa87d87</testSuiteGuid>
   <testCaseLink>
      <guid>4f93e154-276c-47d1-b7a5-2e06b8f8412a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login fail</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c81c38a7-779b-4749-83df-2f2b0b77d9a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eccb83a2-3656-4207-99bc-106a8f8cbe57</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f0497fbc-6352-4ce8-92ac-6b7ca9c15d86</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>0a97ac2c-14f3-4519-9a6a-6409deadd33d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>0a97ac2c-14f3-4519-9a6a-6409deadd33d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>5b908720-8f97-4f3e-88a7-2d574c60c84d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0a97ac2c-14f3-4519-9a6a-6409deadd33d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>1f112a78-b5c8-4d51-b051-ba965ac9049e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
